---
title: "Examining Heart Disease"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, tidy = T)
knitr::knit_engines$set("txt")
```

```{r dependencies, include=FALSE}
# local sources
source("Scripts/utility_functions.R")
source("Scripts/model_functions.R")

# packages
pkgs <- c("dplyr", "popbio", "e1071")
invisible(package.check(pkgs))
```

```{txt echo=FALSE}
==== Table of Contents that we Follow ====
## Executive Summary
## Technical Analysis
### Introduction
### Data Analysis
### Variables' Analysis
### Models
#### Logistic Regression Approach
#### Support Vector Machine (SVM) Approach
### Conclusion
```

## Executive Summary
## Technical Analysis
### Introduction
```{r dataset}
# importing dataset
data_raw = read.csv("./Dataset/Heart.csv")
head(data_raw)
```

### Data Analysis
```{r data structure}
# examining variables
str(data_raw)
```

```{r na displaying}
# examining NA values
summarise_if(data_raw, is.atomic, funs(sum(is.na(.))))
```

```{r predictor naming}
# assigning 0 and 1 to predictor
data_raw$AHD = as.factor(ifelse(data_raw$AHD == "Yes", 1, 0))
```

```{r normalization}
# normalization
cont_list = list(
  Age = data_raw$Age,
  RestBP = data_raw$RestBP,
  Chol = data_raw$Chol,
  MaxHR = data_raw$MaxHR,
  Oldpeak = data_raw$Oldpeak
)

data_raw[, names(cont_list)] <- data.frame(sapply(cont_list, scale))
data_raw %>%
  select(-one_of(c("X"))) %>%
  select_if(is.numeric)  %>%
  head
```

```{r outlier plot, echo=FALSE, fig.height=4, fig.width=6, fig.align="center", fig.cap="Outlier Detection with Boxplot"}
# outlier analysis and removal
boxplot(data_raw[,c(2, 5, 6, 9, 11)], 
        log = "x", 
        las = 2,
        boxwex = 0.3)
```

```{r outlier removal}
# outlier removals on detected variables
data_raw$Chol = outlier_handler(data_raw$Chol)

data_raw$RestBP = outlier_handler(data_raw$RestBP)

data_raw$Oldpeak = outlier_handler(data_raw$Oldpeak)
```

```{r splitting dataset}
# train and test datasets
data_train = data_raw[ 1:250, c(2, 5, 6, 9, 11, 15)]
data_test = data_raw[251:303, c(2, 5, 6, 9, 11, 15)]
```

### Variables' Analysis
```{r correlation plotting}
# correlation between predictor or variables
pairs(AHD ~ Age + RestBP + Chol + MaxHR + Oldpeak, 
      data = data_train,
      diag.panel = panel.hist,
      lower.panel = panel.cor) 
```

```{r dummy guessing}
# assuming all having the disease
t = table(rep(1, 250), data_train$AHD)

# chances
data.frame(all_diseased  = t[1,2] / sum(t), 
           none_diseased = t[1,1] / sum(t))
```

### Models
```{r possible regression models}
# model with all variables
f_0 <- AHD ~ Age + RestBP + Chol + MaxHR + Oldpeak

# other possible models
f_1 <- AHD ~ MaxHR + Oldpeak + RestBP
f_2 <- AHD ~ RestBP + Chol + MaxHR + Oldpeak
f_3 <- AHD ~ Chol + MaxHR + Oldpeak
```

#### Logistic Regression Approach
```{r glm }
# f_1 <- AHD ~ MaxHR + Oldpeak + RestBP
lgm_model = glm(AHD ~ Chol + MaxHR + Oldpeak, data = data_train, family = binomial)
summary(lgm_model)
```

```{r odds ratio}
# odds of variables in the model
ort <- cbind(exp(confint(lgm_model)), 
             Coefficients = coef(lgm_model),
             'Odds Ratio' = exp(coef(lgm_model))) 
round(ort, 2)
```

```{r model plot, echo=FALSE, fig.height=4, fig.width=6, fig.align="center", fig.cap="Model Fit in Data"}
# plotting the model fit on the data
probs <- predict(lgm_model, data_train, type = "response")
logi.hist.plot(probs, 
               data_train$AHD, 
               boxp = F, 
               type = "count", 
               col = "gray", 
               xlabel = "")
```

```{r model interperetation 1}
# goodness-of-fit test
with(lgm_model, 
     pchisq(null.deviance - deviance, 
            df.null - df.residual, 
            lower.tail = F))
```

```{r cutoff plot, echo=FALSE, fig.height=3, fig.width=9, fig.align="center", fig.cap="Cutoff Value Plots"}
# plots for roc, accuracy and prob dist hist
probs <- predict(lgm_model, data_train, type = "response")
rocplot(probs, data_train$AHD)
```

```{r cutoff detection}
# accuracy and cutoff value
cutoff_acc(probs, data_train$AHD)
```

```{r confusion matrix for train}
# decision boundary value from cutoff analysis
db <- unname(cutoff_acc(probs, data_train$AHD)[2,1])

# confusion matrix for train data
probs = predict(lgm_model, data_train, type = "response")
confmatrix(probs, data_train$AHD, db)

```

```{r confusion matrix for test}
# confusion matrix for test data
probs = predict(lgm_model, data_test, type = "response")
confmatrix(probs, data_test$AHD, db)

```

#### Support Vector Machine (SVM) Approach
```{r finding best model with svm tune}
# finding best model with svm tune
if (!exists("svm_tune"))
  svm_tune <- tune(svm, AHD ~ Age + RestBP + Chol + MaxHR + Oldpeak, data = data_train, 
                 type = "C-classification",
                 kernel = "radial", 
                 decision.values = T,
                 scale = F,
                 ranges = list(gamma = 2^(-1:2), cost = 2^(-1:10)))

# first five performances
head(svm_tune$performances)
```

```{r getting best model from tune}
# getting the best model
svm_model <- svm_tune$best.model

# a brief summary of the best model
summary(svm_model)
```

```{r confusion matrix on svm for train data}
# confusion matrix for svm on train data
preds <- predict(svm_model, data_train)
confmatrix(preds, data_train$AHD)
```

```{r svm roc curve on train data, echo=FALSE, fig.height=3, fig.width=9, fig.align="center", fig.cap="SVM ROC for Train Data"}
# roc curve graphs for svm on train data
preds1 <- predict(svm_model, data_train, decision.values = T)
attrs1 <- attributes(preds1)$decision.values

rocplot(attrs1, data_train$AHD)
```

```{r confusion matrix on svm for test data}
# confusion matrix for svm on test data
preds <- predict(svm_model, data_test)
confmatrix(preds, data_test$AHD)
```

```{r svm roc curve on test data, echo=FALSE, fig.height=3, fig.width=9, fig.align="center", fig.cap="SVM ROC for Test Data"}
# roc curve graphs for svm on test data
preds2 <- predict(svm_model, data_test, decision.values = T)
attrs2 <- attributes(preds2)$decision.values

rocplot(attrs2, data_test$AHD)
```

```{r comparing rocs, echo=FALSE, fig.height=3, fig.width=7, fig.align="center", fig.cap="Comparison between ROC Curves"}
# comparing rocs
rocplot_compare(attrs1, attrs2, data_train$AHD, data_test$AHD)
```

### Conclusion

